server:
  port: 8080            # 服务端口

spring:
  profiles:
    active: dev        # 激活配置环境
  servlet:
    multipart:
      max-file-size: 100MB                       # 文件大小上限
      max-request-size: 1000MB                   # 请求大小上限
  main:
    allow-circular-references: true     # 循环依赖
  datasource: # MySQL数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${CloudBike.datasource.host}:${CloudBike.datasource.port}/${CloudBike.datasource.database}
    username: ${CloudBike.datasource.username}
    password: ${CloudBike.datasource.password}

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler    # 枚举类型处理器
    map-underscore-to-camel-case: true                                                          # 驼峰映射
  global-config:
    db-config:
      id-type: auto                 # 主键自增

cloudbike:
  jwt:
    admin-secret-key: CloudBike
    admin-ttl: 7200000
    admin-token-name: adminToken
    user-secret-key: CloudBike
    user-ttl: 7200000
    user-token-name: userToken
  alioss:
    endpoint: ${CloudBike.alioss.endpoint}
    access-key-id: ${CloudBike.alioss.access-key-id}
    access-key-secret: ${CloudBike.alioss.access-key-secret}
    bucket-name: ${CloudBike.alioss.bucket-name}
  wechat:
    appid: ${CloudBike.wechat.appid}
    secret: ${CloudBike.wechat.secret}